### ISSUE TITLE
Questions about "Algorithm 2. Reduce misprefetching per XPLine"

### ISSUE THREAD

**Issue by xywoo-cs** [lingfenghsiang/Persistent-Memory-Study#1]
Hi! This is a great work!   

But I'm having some problems in understanding the open-sourced codes about the "algorithm 2. Reduce misprefetching per XPLine". According to the paper, we should transfer data from PM to DRAM by AVX512 and then load from DRAM.  

---

https://github.com/lingfenghsiang/Persistent-Memory-Study/blob/5e9311a39645f744ad05a8909223297e9140e2c6/run.py#L128-L147

And the codes above show that the "optimized PM" part should be in `test 8`, which is `extreme_case_prefetching()`  

https://github.com/lingfenghsiang/Persistent-Memory-Study/blob/5e9311a39645f744ad05a8909223297e9140e2c6/micro_benchmarks/cases/prefetching.cpp#L168-L186

I'm confused about why `_mm256_stream_load_si256()` can implement algorithm 2. Isn't `__m256i bit256_buf` in registers?

Thanks!

**Comment by lingfenghsiang** [comment]
Hi, thanks for pointing this out. I thought `__m256i bit256_buf` was on the function stack. By checking the assembly code, I found the compiler would put `__m256i bit256_buf` on the register by default.

Algorithm 2 essentially saves the bandwidth on persistent memory by avoiding triggering prefetching. With the buffer on the register, the bandwidth is also saved. It's just faster than the in-memory buffer.

You could use  `volatile __m256i bit256_buf` to put the buffer on memory.

**Comment by xywoo-cs** [comment]
Thanks for your reply!

I still don't get it. Registers are not like DRAM, they are the real locations (units) that CPU can control. Read something from DRAM also introduces data movement from DRAM to registers. btw, isn't `__m256i` designed for integer sse register?  

As far as I know, `memcpy()` in glibc also uses SIMD to move aligned data, so is there any difference?

**Comment by lingfenghsiang** [comment]
Thanks for your feedback.
1. Reading something from DRAM may involve movements to registers or may not. It depends on the compiler. The "MOV" instructions of x86 also support moving data from one address to another. A straightforward way to check this is to use gdb and step over the instructions as the program reads DRAM. As long as you don't touch the address of the cacheline too much, the prefetching could be avoided.
2. `__m256i` is intended for integer sse register. It only hints the compiler to put it on the register but cannot enforce it. I checked my assembly code using `gdb` and found `volatile __m256i bit256_buf` on DRAM. BTW, here I enclose a link from the community.  Maybe [this](https://community.intel.com/t5/Intel-ISA-Extensions/Is-it-ok-to-create-an-array-of-m256i/m-p/996279) would help.
3. `memcpy()` is intended to provide universal support across platforms. There are older CPU models that do not support 256/512 bit data manipulation. If your `glibc` enables 256-bit or 512-bit data manipulation,  it's essentially the same as the code in this repository. Note that copy is not the only way to read memory. If you have a bunch of pointers pointing to data on the persistent memory, dereferencing these pointers is also touching the address on the memory, which may trigger prefetching.

**Comment by xywoo-cs** [comment]
I get it. Thank you for such a detailed reply!
