### ISSUE TITLE
Questions about "Reduce misprefetching per XPLine" by AVX load

### ISSUE THREAD

**Issue by xywoo-cs** [lingfenghsiang/Persistent-Memory-Study#2]
Hello! I'm very interested in this paper. But I'm having some trouble reproducing the results. (I would be very grateful if you could give me some advice.)  🙏

1.  AVX load WILL introduce prefetching in loops   

The following code does not incur prefetching like you mentioned in paper.
```
__m512i dst_512;
dst_512 ^= _mm512_stream_load_si512((__m512i *)(rand_aligned_addr + 64 * 0));
dst_512 ^= _mm512_stream_load_si512((__m512i *)(rand_aligned_addr + 64 * 1));
dst_512 ^= _mm512_stream_load_si512((__m512i *)(rand_aligned_addr + 64 * 2));
dst_512 ^= _mm512_stream_load_si512((__m512i *)(rand_aligned_addr + 64 * 3));
```

but once I turn the process above into loop:
```
__m512i dst_512;
for (int i = 0; i < 4; i++) {
    dst_512 ^= _mm512_stream_load_si512((__m512i *)(rand_aligned_addr + 64 * i));
}
```

It shockingly enables prefetching again.  note: I disable alld optimization options in g++.

2. I am curious why AVX load doesn't trigger prefetching, there is no relevant material in the paper and I did not retrieve information about it. The only thing that might be relevant is **non-temporal load in WC memory**, but even with normal AVX load (*not in loops*), prefetching is not triggered. if there is more explanation behind this phenomenon?

Thanks!!

**Comment by lingfenghsiang** [comment]
Hi,
Thanks for your interest.
1. Regarding your code. I suspect that your CPU speculatively executes some AVX512 instructions as it goes through the branching in the for loop. Even though you don't mean to access the memory, unretired instructions do access more memory than desired.
2. In terms of hardware prefetching. One of the most significant prefetching activities stems from RCU stream prefetcher. It prefetches another cacheline once you touch the current cacheline frequently enough (e.g. more than three times), which is not emphasized in documents. You may find clues from the community and verify this on your own:
https://stackoverflow.com/questions/53517653/in-which-condition-dcu-prefetcher-start-prefetching

**Comment by xywoo-cs** [comment]
Thanks for your answer again. This is an insightful work!
